[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "hypercorn app.main:app --bind 0.0.0.0:$PORT --workers 4"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 5
