[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -c gunicorn_conf.py app.main:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 5
