services:
  - type: web
    name: yupoo-extractor
    env: docker
    buildCommand: docker build -t yupoo-extractor .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yupoo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString

  - type: worker
    name: yupoo-celery-worker
    env: docker
    buildCommand: docker build -t yupoo-worker .
    startCommand: celery -A app.tasks worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yupoo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString

  - type: redis
    name: yupoo-redis
    plan: free
    ipAllowList: []

databases:
  - name: yupoo-db
    databaseName: yupoo
    plan: free
