services:
  - type: web
    name: yupoo-extractor
    env: docker
    buildCommand: docker build -t yupoo-extractor .
    startCommand: /start.sh
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 100
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: yupoo-db
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: yupoo-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: yupoo-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: yupoo-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: yupoo-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: yupoo-db
          property: database
      - key: REDIS_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

  - type: worker
    name: yupoo-celery-worker
    env: docker
    buildCommand: docker build -t yupoo-worker .
    startCommand: celery -A app.tasks worker --loglevel=info
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yupoo-db
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: yupoo-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: yupoo-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: yupoo-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: yupoo-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: yupoo-db
          property: database
      - key: REDIS_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: yupoo-redis
          type: redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

  - type: redis
    name: yupoo-redis
    plan: free
    ipAllowList: []

databases:
  - name: yupoo-db
    databaseName: yupoo
    plan: free
    ipAllowList: []
